default-group: Joueur

redis-sentinel:
   enabled: false
   master: masterName
   auth: authpassword
   sentinels:
      - ip:port
      - ip:port

redis:
   enabled: false
   auth: authpassword
   address: ip
   port: port


sql:
  enabled: false
  host: host
  port: 3306
  database: database
  user: user
  password: password